@isTest
public class RFQAcceptedRejectedTest {
    // @testSetup
    // static void setupMethod(){
    //     buildertek__RFQ_Template_Settings__c cs = new buildertek__RFQ_Template_Settings__c();
    //     cs.buildertek__Sites_URL__c = 'test.com';
    //     insert cs;
    //     buildertek__Admin_Interface_Node_Configuration__c admin = new buildertek__Admin_Interface_Node_Configuration__c();
    //     admin.Name = 'RFQ Configuration';
    //     admin.buildertek__Color_code__c ='#b44f18';
    //     buildertek__RFQ_Template_Settings__c customSetting = new buildertek__RFQ_Template_Settings__c();
    //     customSetting.Name = 'buildertek__Sites_URL__c';
    //     customSetting.buildertek__Sites_URL__c = 'https://btservice360-dev-ed.my.salesforce-sites.com';
    //     insert customSetting;
    // }
    
    // @isTest
    // static void testMethod1(){
    //     RFQAcceptedRejected rfq = new RFQAcceptedRejected();  
    // }
}